import { getDb } from "@/lib/db";
import { PageHeader } from "@/components/dashboard/shell";
import { Panel, DataTable, Td, StatCard } from "@/components/dashboard/widgets";
import { EmptyState } from "@/components/ui/primitives";
import { formatMoney } from "@/lib/money";

export default async function PayoutsPage({ params }: { params: Promise<{ rid: string }> }) {
  const { rid } = await params;
  const db = getDb();
  const r = (await db.get("restaurants", rid))!;
  const [payouts, unsettled] = await Promise.all([
    db.list("payouts", { restaurant_id: rid }, { orderBy: "created_at", ascending: false }),
    db.list("orders", { restaurant_id: rid, status: "delivered", payout_id: null }),
  ]);
  const pendingAmount = unsettled.reduce((s, o) => s + o.restaurant_payout_cents, 0);
  const fmt = (c: number) => formatMoney(c, r.currency);
  const date = (iso: string) => new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: r.timezone });
  return (
    <>
      <PageHeader title="Payouts" description="Settlements are generated by the platform team. Each shows your sales, the commission and the net amount." />
      <div className="grid gap-4 sm:grid-cols-3">
        <StatCard tone="dark" label="Unsettled orders" value={unsettled.length} sub="Completed, not yet in a payout" />
        <StatCard label="Unsettled earnings" value={fmt(pendingAmount)} sub="Before cash-collection adjustments" />
        <StatCard label="Paid to date" value={fmt(payouts.filter((p) => p.status === "paid").reduce((s, p) => s + p.amount_cents, 0))} />
      </div>
      <Panel title="Payout history" className="mt-6">
        {payouts.length === 0 ? <div className="p-5"><EmptyState title="No payouts yet">Your first payout will appear after the next settlement run.</EmptyState></div> : (
          <DataTable head={["Period", "Orders", "Sales", "Commission", "Adjustments", "Net", "Status"]}>
            {payouts.map((p) => (
              <tr key={p.id}>
                <Td>{date(p.period_start)} – {date(p.period_end)}</Td>
                <Td>{p.order_count}</Td>
                <Td>{fmt(p.gross_sales_cents)}</Td>
                <Td>−{fmt(p.commission_cents)}</Td>
                <Td>{p.adjustments_cents ? fmt(p.adjustments_cents) : "—"}</Td>
                <Td className="font-bold">{p.amount_cents < 0 ? `Due to platform ${fmt(-p.amount_cents)}` : fmt(p.amount_cents)}</Td>
                <Td><span className="capitalize">{p.status}</span>{p.reference && <span className="block text-xs text-night-600">Ref {p.reference}</span>}</Td>
              </tr>
            ))}
          </DataTable>
        )}
      </Panel>
      <p className="mt-4 text-xs text-night-600">Adjustments cover cash and card payments your restaurant collected directly on pickup orders; that money is already with you, so the platform&apos;s share is deducted.</p>
    </>
  );
}
